rootProject.name = "TheMovieViewer"
include(":app")
include(":core-model")
include(":core-data")
include(":core-ui")
include(":core-common")
include(":feature-movielist")
include(":feature-favorites")
include(":feature-details")
include(":feature-people")
include(":core-datastore")
include(":core-database")
